version: "3.9"

services:

  postgres:
    image: postgres:15.2
    container_name: postgres_db
    ports:
      - 27017:5432  # for some reason, my desktop PC refuses connections on 5432 (I probably broke something up there), so this maps the DB port to 27017 on my desktop
    expose:
      - 5432
    env_file:
      - .env
    networks:
      - ghost
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  ghost:

volumes:
  pgdata:
#    external: true