version: '3.9'

services:

  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - 27017:27017
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ghost-admin
      MONGO_INITDB_ROOT_PASSWORD: ghost-admin-password
      MONGO_INITDB_DATABASE: ghostdb
    #env_file:
    #  - mongo.env
    networks:
      - ghost
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongo_data:/data/db
      - mongo_config:/data/configdb

#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

networks:
  ghost:

volumes:
  mongo_data:
  mongo_config: