version: "3.9"

services:

  postgres:
    image: postgres:15.2
    container_name: postgres_db
    ports:
      - 5432:5432
    expose:
      - 5432
    env_file:
      - .env
    networks:
      - ghost
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  ghost:

volumes:
  pgdata:
#    external: true